[project]
name = "inventory"
version = "0.1.0"
description = "Dagster tutorial project for multiple code locations."
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "cowsay==5.0",
    "dagster",
    "dagster-cloud",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dagster]
module_name = "src.inventory.definitions"
code_location_name = "inventory"
