[project]
name = "Sales"
version = "0.1.0"
description = "Dagster tutorial project for multiple code locations."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "cowsay==6.1",
    "dagster",
    "dagster-cloud",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dagster]
module_name = "src.sales.definitions"
code_location_name = "sales"
